### ISSUE TITLE
Publish to Sketchpacks

### ISSUE THREAD

**Issue by DiogoBatista** [themainingredient/colormate#37]
- [x] Setup a unique identifier (https://docs.sketchpacks.com/developers/publishing/identifiers.html)
- [x] Create a `.sketchpacks.json` in the root of the project as such
```
{
  "schema_version": "1.0.0",
  "manifest_path": "path/to/your/manifest.json",
  "appcast_path": "path/to/your/appcast.xml"
}
```
- [x] host appcast.xml in the repository
- [ ] ~~change ci/cd to use skpm instead semantic-release~~
- [ ] ~~remove semantic-release flow and package~~
- [ ] ~~use skpm to publish and update the repo~~
- [x] build and zip plugin folder 
- [x] push zipped plugin to github repo
- [x] install sketch relay in repo (https://github.com/integration/sketchpacks-relay)

**Comment by Iar0** [comment]
I'll close this because of the following:

- no support from sketchpacks, we did not get any reply to our email;
- our current pipeline use semantic-release and, when we release, on sketchpacks we only get the source code and not any plugin (that is correctly in the release assets). 
- Skpm would be the way to go and it actually works, but the current implementation does not permit a different commit message. Because of this, the master pipeline keeps triggering on CI.
